-- 코드를 입력하세요
SELECT A.PRODUCT_ID, PRODUCT_NAME, PRICE*AMOUNT AS TOTAL_SALE
FROM FOOD_PRODUCT AS A JOIN (SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT FROM FOOD_ORDER WHERE YEAR(PRODUCE_DATE) = '2022' AND MONTH(PRODUCE_DATE) = '5' GROUP BY PRODUCT_ID) AS B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALE DESC, A.PRODUCT_ID
